-- Series 50SN products (32, all priced) + filter values. Run AFTER seed_series_50sn_info.sql.
DECLARE @SeriesName nvarchar(100) = N'Series 50SN';
DECLARE @CategoryId int = (SELECT CategoryId FROM Categories WHERE Name = @SeriesName);

INSERT INTO Filters (Name) SELECT v.Name FROM (VALUES (N'Size'),(N'End Connection'),(N'Operating Pressure'),(N'Seat')) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Filters f WHERE f.Name = v.Name);

INSERT INTO CategoryFilters (CategoryId, FilterId, SortOrder)
SELECT @CategoryId, f.FilterId, v.SortOrder
FROM (VALUES (N'End Connection',0),(N'Size',1),(N'Seat',2),(N'Operating Pressure',3)) AS v(FilterName, SortOrder)
JOIN Filters f ON f.Name = v.FilterName
WHERE NOT EXISTS (SELECT 1 FROM CategoryFilters cf WHERE cf.CategoryId=@CategoryId AND cf.FilterId=f.FilterId);

INSERT INTO CatalogProducts (PartNumber, CategoryId, ProductStatus, FamilyDescription, DetailDescription, ImageUrl, Price) VALUES
(N'V50SN-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 32.80),
(N'V50SN-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 38.65),
(N'V50SN-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 32.03),
(N'V50SN-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 37.88),
(N'V50SN-3-4IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3/4", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 32.65),
(N'V50SN-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3/4", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 41.73),
(N'V50SN-3-4IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3/4", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 31.72),
(N'V50SN-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3/4", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 40.96),
(N'V50SN-1IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 44.20),
(N'V50SN-1IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 52.67),
(N'V50SN-1IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 43.27),
(N'V50SN-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 51.59),
(N'V50SN-1-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 83.62),
(N'V50SN-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 103.03),
(N'V50SN-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 81.47),
(N'V50SN-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 1 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 101.02),
(N'V50SN-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 116.27),
(N'V50SN-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 143.84),
(N'V50SN-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 113.04),
(N'V50SN-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 1000 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 140.60),
(N'V50SN-2-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 215.75),
(N'V50SN-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 288.60),
(N'V50SN-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 210.36),
(N'V50SN-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 2 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 283.21),
(N'V50SN-3IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 291.68),
(N'V50SN-3IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 385.92),
(N'V50SN-3IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 283.98),
(N'V50SN-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 3", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 378.22),
(N'V50SN-4IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 4", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 501.27),
(N'V50SN-4IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 4", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 717.49),
(N'V50SN-4IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 4", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 488.49),
(N'V50SN-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 50SN Three-Piece Sanitary Ball Valve', N'V50SN - 3-PC Sanitary Ball Valve, 800 PSI, Body + Ball CF8M, Stem SS316, End Cap CF3M, Internal Polished / External Machining, With Locking Device, 4", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-50sn.png', 704.70);

INSERT INTO ProductFilterValues (ProductId, CategoryId, FilterId, Value)
SELECT p.ProductId, p.CategoryId, f.FilterId, v.Value
FROM CatalogProducts p
JOIN (VALUES
  (N'V50SN-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1/2"'),(N'V50SN-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1/2"'),(N'V50SN-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1/2"'),(N'V50SN-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1/2"'),(N'V50SN-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'3/4"'),(N'V50SN-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'3/4"'),(N'V50SN-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'3/4"'),(N'V50SN-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'3/4"'),(N'V50SN-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1"'),(N'V50SN-1IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-1IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1"'),(N'V50SN-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1"'),(N'V50SN-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1"'),(N'V50SN-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1 1/2"'),(N'V50SN-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1 1/2"'),(N'V50SN-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1 1/2"'),(N'V50SN-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1 1/2"'),(N'V50SN-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'2"'),(N'V50SN-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'2"'),(N'V50SN-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'2"'),(N'V50SN-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'2"'),(N'V50SN-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V50SN-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'2 1/2"'),(N'V50SN-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'2 1/2"'),(N'V50SN-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'2 1/2"'),(N'V50SN-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'2 1/2"'),(N'V50SN-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-3IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'3"'),(N'V50SN-3IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-3IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-3IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'3"'),(N'V50SN-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'3"'),(N'V50SN-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'3"'),(N'V50SN-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-4IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'4"'),(N'V50SN-4IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V50SN-4IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-4IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'4"'),(N'V50SN-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V50SN-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'4"'),(N'V50SN-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V50SN-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V50SN-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V50SN-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'4"'),(N'V50SN-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V50SN-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V50SN-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI')
) AS v(PartNumber, FilterName, Value) ON v.PartNumber = p.PartNumber
JOIN Filters f ON f.Name = v.FilterName WHERE p.CategoryId=@CategoryId;

SELECT COUNT(*) AS Products FROM CatalogProducts WHERE CategoryId=@CategoryId;
SELECT COUNT(*) AS FilterValues FROM ProductFilterValues WHERE CategoryId=@CategoryId;
