-- Series 77SN products (32, all priced) + filter values. Run AFTER seed_series_77sn_info.sql.
DECLARE @SeriesName nvarchar(100) = N'Series 77SN';
DECLARE @CategoryId int = (SELECT CategoryId FROM Categories WHERE Name = @SeriesName);

INSERT INTO Filters (Name) SELECT v.Name FROM (VALUES (N'Size'),(N'End Connection'),(N'Operating Pressure'),(N'Seat')) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Filters f WHERE f.Name = v.Name);

INSERT INTO CategoryFilters (CategoryId, FilterId, SortOrder)
SELECT @CategoryId, f.FilterId, v.SortOrder
FROM (VALUES (N'End Connection',0),(N'Size',1),(N'Seat',2),(N'Operating Pressure',3)) AS v(FilterName, SortOrder)
JOIN Filters f ON f.Name = v.FilterName
WHERE NOT EXISTS (SELECT 1 FROM CategoryFilters cf WHERE cf.CategoryId=@CategoryId AND cf.FilterId=f.FilterId);

INSERT INTO CatalogProducts (PartNumber, CategoryId, ProductStatus, FamilyDescription, DetailDescription, ImageUrl, Price) VALUES
(N'V77SN-10-2A-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 43.27),
(N'V77SN-10-2A-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 53.28),
(N'V77SN-10-2A-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 41.27),
(N'V77SN-10-2A-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 51.28),
(N'V77SN-10-2A-3-4IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3/4", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 44.66),
(N'V77SN-10-2A-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3/4", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 54.21),
(N'V77SN-10-2A-3-4IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3/4", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 42.04),
(N'V77SN-10-2A-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3/4", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 51.74),
(N'V77SN-10-2A-1IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 57.29),
(N'V77SN-10-2A-1IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 72.07),
(N'V77SN-10-2A-1IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 54.52),
(N'V77SN-10-2A-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 69.15),
(N'V77SN-10-2A-1-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 116.27),
(N'V77SN-10-2A-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 152.77),
(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 110.42),
(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 1 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 147.07),
(N'V77SN-10-2A-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 151.54),
(N'V77SN-10-2A-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 214.37),
(N'V77SN-10-2A-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 144.30),
(N'V77SN-10-2A-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 1000 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 207.13),
(N'V77SN-10-2A-2-1-2IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2 1/2", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 301.84),
(N'V77SN-10-2A-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2 1/2", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 400.40),
(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2 1/2", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 287.67),
(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 2 1/2", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 386.08),
(N'V77SN-10-2A-3IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 392.24),
(N'V77SN-10-2A-3IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 547.78),
(N'V77SN-10-2A-3IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 373.91),
(N'V77SN-10-2A-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 3", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 529.30),
(N'V77SN-10-2A-4IN-T-CLAMP-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 4", Tri-Clamp, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 645.88),
(N'V77SN-10-2A-4IN-T-CLAMP-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 4", Tri-Clamp, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 879.34),
(N'V77SN-10-2A-4IN-SHORT-WELDING-STD-PTFE-SEAT', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 4", Short Welding, Std PTFE', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 614.77),
(N'V77SN-10-2A-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER', @CategoryId, N'Active', N'Mars Series 77SN Three-Piece Sanitary Ball Valve', N'V77SN-10 2A - 3-PC High Performance Sanitary Ball Valve, Full Port, 800 PSI, Body and End Cap CF3M, Ball CF3M/SS316L, Stem SS316L, Internal Polished / External Machining, 4", Short Welding, PTFE Cavity Filler', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-77sn.png', 848.23);

INSERT INTO ProductFilterValues (ProductId, CategoryId, FilterId, Value)
SELECT p.ProductId, p.CategoryId, f.FilterId, v.Value
FROM CatalogProducts p
JOIN (VALUES
  (N'V77SN-10-2A-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1/2"'),(N'V77SN-10-2A-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1/2"'),(N'V77SN-10-2A-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1/2"'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1/2"'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'3/4"'),(N'V77SN-10-2A-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-3-4IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'3/4"'),(N'V77SN-10-2A-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-3-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'3/4"'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'3/4"'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-3-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1"'),(N'V77SN-10-2A-1IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1"'),(N'V77SN-10-2A-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1"'),(N'V77SN-10-2A-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1"'),(N'V77SN-10-2A-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'1 1/2"'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'1 1/2"'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'1 1/2"'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'1 1/2"'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-1-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'2"'),(N'V77SN-10-2A-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'2"'),(N'V77SN-10-2A-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'2"'),(N'V77SN-10-2A-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'2"'),(N'V77SN-10-2A-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'1000 PSI'),
  (N'V77SN-10-2A-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'2 1/2"'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'2 1/2"'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-2-1-2IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'2 1/2"'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'2 1/2"'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-2-1-2IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-3IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'3"'),(N'V77SN-10-2A-3IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-3IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-3IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'3"'),(N'V77SN-10-2A-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-3IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'3"'),(N'V77SN-10-2A-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-3IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'3"'),(N'V77SN-10-2A-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-3IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-4IN-T-CLAMP-STD-PTFE-SEAT',N'Size',N'4"'),(N'V77SN-10-2A-4IN-T-CLAMP-STD-PTFE-SEAT',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-4IN-T-CLAMP-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-4IN-T-CLAMP-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Size',N'4"'),(N'V77SN-10-2A-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'End Connection',N'Tri-Clamp'),(N'V77SN-10-2A-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-4IN-T-CLAMP-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Size',N'4"'),(N'V77SN-10-2A-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Seat',N'Std PTFE'),(N'V77SN-10-2A-4IN-SHORT-WELDING-STD-PTFE-SEAT',N'Operating Pressure',N'800 PSI'),
  (N'V77SN-10-2A-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Size',N'4"'),(N'V77SN-10-2A-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'End Connection',N'Short Welding'),(N'V77SN-10-2A-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Seat',N'PTFE Cavity Filler'),(N'V77SN-10-2A-4IN-SHORT-WELDING-PTFE-CAVITY-FILLER',N'Operating Pressure',N'800 PSI')
) AS v(PartNumber, FilterName, Value) ON v.PartNumber = p.PartNumber
JOIN Filters f ON f.Name = v.FilterName WHERE p.CategoryId=@CategoryId;

SELECT COUNT(*) AS Products FROM CatalogProducts WHERE CategoryId=@CategoryId;
SELECT COUNT(*) AS FilterValues FROM ProductFilterValues WHERE CategoryId=@CategoryId;
