-- Series 22 products (60) + filter values. Run AFTER seed_series_22_info.sql.
DECLARE @SeriesName nvarchar(100) = N'Series 22';
DECLARE @CategoryId int = (SELECT CategoryId FROM Categories WHERE Name = @SeriesName);

-- Filters (global, idempotent)
INSERT INTO Filters (Name) SELECT v.Name FROM (VALUES (N'Size'),(N'End Connection'),(N'Operating Pressure'),(N'Handle')) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Filters f WHERE f.Name = v.Name);

-- CategoryFilters for Series 22 (idempotent)
INSERT INTO CategoryFilters (CategoryId, FilterId, SortOrder)
SELECT @CategoryId, f.FilterId, v.SortOrder
FROM (VALUES (N'End Connection',0),(N'Size',1),(N'Operating Pressure',2),(N'Handle',3)) AS v(FilterName, SortOrder)
JOIN Filters f ON f.Name = v.FilterName
WHERE NOT EXISTS (SELECT 1 FROM CategoryFilters cf WHERE cf.CategoryId=@CategoryId AND cf.FilterId=f.FilterId);

-- Products
INSERT INTO CatalogProducts (PartNumber, CategoryId, ProductStatus, FamilyDescription, DetailDescription, ImageUrl, Price) VALUES
(N'V22-1-4IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-4IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-1-4IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-4IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-1-4IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-4IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/4", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-3-8IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-3-8IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-3-8IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-3-8IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-3-8IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-3-8IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/8", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-1-2IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-2IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-1-2IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-2IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-1-2IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 21.87),
(N'V22-1-2IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1/2", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.18),
(N'V22-3-4IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.64),
(N'V22-3-4IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 26.95),
(N'V22-3-4IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.64),
(N'V22-3-4IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 26.95),
(N'V22-3-4IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 24.64),
(N'V22-3-4IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3/4", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 26.95),
(N'V22-1IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 35.73),
(N'V22-1IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 38.81),
(N'V22-1IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 35.73),
(N'V22-1IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 38.81),
(N'V22-1IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 35.73),
(N'V22-1IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 38.81),
(N'V22-1-1-4IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 44.20),
(N'V22-1-1-4IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 47.43),
(N'V22-1-1-4IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 44.20),
(N'V22-1-1-4IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 47.43),
(N'V22-1-1-4IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 44.20),
(N'V22-1-1-4IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/4", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 47.43),
(N'V22-1-1-2IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 73.30),
(N'V22-1-1-2IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 78.23),
(N'V22-1-1-2IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 73.30),
(N'V22-1-1-2IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 78.23),
(N'V22-1-1-2IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 73.30),
(N'V22-1-1-2IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 1 1/2", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 78.23),
(N'V22-2IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 94.09),
(N'V22-2IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 99.02),
(N'V22-2IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 94.09),
(N'V22-2IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 99.02),
(N'V22-2IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 94.09),
(N'V22-2IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 99.02),
(N'V22-2-1-2IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 170.48),
(N'V22-2-1-2IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 177.41),
(N'V22-2-1-2IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 170.48),
(N'V22-2-1-2IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 177.41),
(N'V22-2-1-2IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 170.48),
(N'V22-2-1-2IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 2 1/2", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 177.41),
(N'V22-3IN-BSP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", BSP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 230.85),
(N'V22-3IN-BSP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", BSP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 237.78),
(N'V22-3IN-BSPP-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", BSPP, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 230.85),
(N'V22-3IN-BSPP-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", BSPP, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 237.78),
(N'V22-3IN-NPT-BARE-SHAFT', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", NPT, Bare Shaft', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 230.85),
(N'V22-3IN-NPT-W-HANDLE', @CategoryId, N'Active', N'Mars Ball Valve Series 22 Full Bore Direct Mount', N'V22 - 2-PC Ball Valve, Full Port, ISO 5211 Mounting Pad, 1000 PSI, Ball CF8M, Stem SS316, Seat and Seal PTFE, 3", NPT, W Handle', N'https://pblol2.blob.core.windows.net/mars-valves/ball-valves/series-22.jpg', 237.78);

-- Filter values (Size, End Connection, Handle, Operating Pressure)
INSERT INTO ProductFilterValues (ProductId, CategoryId, FilterId, Value)
SELECT p.ProductId, p.CategoryId, f.FilterId, v.Value
FROM CatalogProducts p
JOIN (VALUES
  (N'V22-1-4IN-BSP-BARE-SHAFT',N'Size',N'1/4"'),(N'V22-1-4IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-1-4IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-4IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-4IN-BSP-W-HANDLE',N'Size',N'1/4"'),(N'V22-1-4IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-1-4IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-4IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-4IN-BSPP-BARE-SHAFT',N'Size',N'1/4"'),(N'V22-1-4IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-1-4IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-4IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-4IN-BSPP-W-HANDLE',N'Size',N'1/4"'),(N'V22-1-4IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-1-4IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-4IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-4IN-NPT-BARE-SHAFT',N'Size',N'1/4"'),(N'V22-1-4IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-1-4IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-4IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-4IN-NPT-W-HANDLE',N'Size',N'1/4"'),(N'V22-1-4IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-1-4IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-4IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-BSP-BARE-SHAFT',N'Size',N'3/8"'),(N'V22-3-8IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-3-8IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-8IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-BSP-W-HANDLE',N'Size',N'3/8"'),(N'V22-3-8IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-3-8IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-8IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-BSPP-BARE-SHAFT',N'Size',N'3/8"'),(N'V22-3-8IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-3-8IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-8IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-BSPP-W-HANDLE',N'Size',N'3/8"'),(N'V22-3-8IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-3-8IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-8IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-NPT-BARE-SHAFT',N'Size',N'3/8"'),(N'V22-3-8IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-3-8IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-8IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-8IN-NPT-W-HANDLE',N'Size',N'3/8"'),(N'V22-3-8IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-3-8IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-8IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-BSP-BARE-SHAFT',N'Size',N'1/2"'),(N'V22-1-2IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-1-2IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-2IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-BSP-W-HANDLE',N'Size',N'1/2"'),(N'V22-1-2IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-1-2IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-2IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-BSPP-BARE-SHAFT',N'Size',N'1/2"'),(N'V22-1-2IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-1-2IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-2IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-BSPP-W-HANDLE',N'Size',N'1/2"'),(N'V22-1-2IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-1-2IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-2IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-NPT-BARE-SHAFT',N'Size',N'1/2"'),(N'V22-1-2IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-1-2IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-2IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-2IN-NPT-W-HANDLE',N'Size',N'1/2"'),(N'V22-1-2IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-1-2IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-2IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-BSP-BARE-SHAFT',N'Size',N'3/4"'),(N'V22-3-4IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-3-4IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-4IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-BSP-W-HANDLE',N'Size',N'3/4"'),(N'V22-3-4IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-3-4IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-4IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-BSPP-BARE-SHAFT',N'Size',N'3/4"'),(N'V22-3-4IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-3-4IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-4IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-BSPP-W-HANDLE',N'Size',N'3/4"'),(N'V22-3-4IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-3-4IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-4IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-NPT-BARE-SHAFT',N'Size',N'3/4"'),(N'V22-3-4IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-3-4IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3-4IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3-4IN-NPT-W-HANDLE',N'Size',N'3/4"'),(N'V22-3-4IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-3-4IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3-4IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-BSP-BARE-SHAFT',N'Size',N'1"'),(N'V22-1IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-1IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-BSP-W-HANDLE',N'Size',N'1"'),(N'V22-1IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-1IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-BSPP-BARE-SHAFT',N'Size',N'1"'),(N'V22-1IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-1IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-BSPP-W-HANDLE',N'Size',N'1"'),(N'V22-1IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-1IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-NPT-BARE-SHAFT',N'Size',N'1"'),(N'V22-1IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-1IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1IN-NPT-W-HANDLE',N'Size',N'1"'),(N'V22-1IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-1IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-BSP-BARE-SHAFT',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-1-1-4IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-4IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-BSP-W-HANDLE',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-1-1-4IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-4IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-BSPP-BARE-SHAFT',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-1-1-4IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-4IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-BSPP-W-HANDLE',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-1-1-4IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-4IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-NPT-BARE-SHAFT',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-1-1-4IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-4IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-4IN-NPT-W-HANDLE',N'Size',N'1 1/4"'),(N'V22-1-1-4IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-1-1-4IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-4IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-BSP-BARE-SHAFT',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-1-1-2IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-2IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-BSP-W-HANDLE',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-1-1-2IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-2IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-BSPP-BARE-SHAFT',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-1-1-2IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-2IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-BSPP-W-HANDLE',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-1-1-2IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-2IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-NPT-BARE-SHAFT',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-1-1-2IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-1-1-2IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-1-1-2IN-NPT-W-HANDLE',N'Size',N'1 1/2"'),(N'V22-1-1-2IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-1-1-2IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-1-1-2IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-BSP-BARE-SHAFT',N'Size',N'2"'),(N'V22-2IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-2IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-BSP-W-HANDLE',N'Size',N'2"'),(N'V22-2IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-2IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-BSPP-BARE-SHAFT',N'Size',N'2"'),(N'V22-2IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-2IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-BSPP-W-HANDLE',N'Size',N'2"'),(N'V22-2IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-2IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-NPT-BARE-SHAFT',N'Size',N'2"'),(N'V22-2IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-2IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2IN-NPT-W-HANDLE',N'Size',N'2"'),(N'V22-2IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-2IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-BSP-BARE-SHAFT',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-2-1-2IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2-1-2IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-BSP-W-HANDLE',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-2-1-2IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2-1-2IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-BSPP-BARE-SHAFT',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-2-1-2IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2-1-2IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-BSPP-W-HANDLE',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-2-1-2IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2-1-2IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-NPT-BARE-SHAFT',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-2-1-2IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-2-1-2IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-2-1-2IN-NPT-W-HANDLE',N'Size',N'2 1/2"'),(N'V22-2-1-2IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-2-1-2IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-2-1-2IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-BSP-BARE-SHAFT',N'Size',N'3"'),(N'V22-3IN-BSP-BARE-SHAFT',N'End Connection',N'BSP'),(N'V22-3IN-BSP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3IN-BSP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-BSP-W-HANDLE',N'Size',N'3"'),(N'V22-3IN-BSP-W-HANDLE',N'End Connection',N'BSP'),(N'V22-3IN-BSP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3IN-BSP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-BSPP-BARE-SHAFT',N'Size',N'3"'),(N'V22-3IN-BSPP-BARE-SHAFT',N'End Connection',N'BSPP'),(N'V22-3IN-BSPP-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3IN-BSPP-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-BSPP-W-HANDLE',N'Size',N'3"'),(N'V22-3IN-BSPP-W-HANDLE',N'End Connection',N'BSPP'),(N'V22-3IN-BSPP-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3IN-BSPP-W-HANDLE',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-NPT-BARE-SHAFT',N'Size',N'3"'),(N'V22-3IN-NPT-BARE-SHAFT',N'End Connection',N'NPT'),(N'V22-3IN-NPT-BARE-SHAFT',N'Handle',N'Bare Shaft'),(N'V22-3IN-NPT-BARE-SHAFT',N'Operating Pressure',N'1000 PSI'),
  (N'V22-3IN-NPT-W-HANDLE',N'Size',N'3"'),(N'V22-3IN-NPT-W-HANDLE',N'End Connection',N'NPT'),(N'V22-3IN-NPT-W-HANDLE',N'Handle',N'W Handle'),(N'V22-3IN-NPT-W-HANDLE',N'Operating Pressure',N'1000 PSI')
) AS v(PartNumber, FilterName, Value) ON v.PartNumber = p.PartNumber COLLATE DATABASE_DEFAULT
JOIN Filters f ON f.Name = v.FilterName
WHERE p.CategoryId = @CategoryId;

SELECT COUNT(*) AS Products FROM CatalogProducts WHERE CategoryId=@CategoryId;
SELECT COUNT(*) AS FilterValues FROM ProductFilterValues WHERE CategoryId=@CategoryId;
